import { JsonValue } from "type-fest";

export type Delivery = {
  actualDeliveryTime: Date | null;
  actualPickupTime: Date | null;
  cancellationReason: string | null;
  cancelledAt: Date | null;
  createdAt: Date;
  currency: string | null;
  currentLocation: string | null;
  customerId: number | null;
  deliveryAddress: string | null;
  deliveryContactName: string | null;
  deliveryContactPhone: string | null;
  deliveryCoords: string | null;
  deliveryInstructions: string | null;
  deliveryTimeWindow: JsonValue;
  dimensions: JsonValue;
  discount: number | null;
  distance: number | null;
  driverId: number | null;
  estimatedArrival: Date | null;
  estimatedTime: number | null;
  feedback: string | null;
  id: string;
  isFragile: boolean | null;
  notes: string | null;
  orderNumber: string | null;
  packageSize: string | null;
  packageType: string | null;
  paymentMethod: string | null;
  paymentStatus: string | null;
  pickupAddress: string | null;
  pickupContactName: string | null;
  pickupContactPhone: string | null;
  pickupCoords: string | null;
  pickupInstructions: string | null;
  pickupTimeWindow: JsonValue;
  price: number | null;
  priority: number | null;
  progress: number | null;
  promoCode: string | null;
  proofOfDelivery: string | null;
  requiresRefrigeration: boolean | null;
  routeId: number | null;
  scheduledDate: Date | null;
  signature: string | null;
  status: string | null;
  tags?: Array<"Option1">;
  trackingNumber: string | null;
  trackingUrl: string | null;
  typeField: string | null;
  updatedAt: Date;
  weight: number | null;
};
